import React from 'react';
import { X, Download, FileText, Activity, Users, Building, DollarSign, Calendar } from 'lucide-react';

const DashboardReportModal = ({ isOpen, onClose, stats, topVenues, recentLogs }) => {
    if (!isOpen) return null;

    const currentDate = new Date().toLocaleDateString('en-US', {
        weekday: 'long',
        year: 'numeric',
        month: 'long',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
    });

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm">
            <div className="bg-white w-full max-w-4xl max-h-[90vh] overflow-y-auto rounded-3xl shadow-2xl animate-in fade-in zoom-in-95 duration-200 px-8 py-10 relative">

                {/* Close Button */}
                <button
                    onClick={onClose}
                    className="absolute top-6 right-6 p-2 bg-gray-100 hover:bg-gray-200 rounded-full transition-colors"
                >
                    <X size={20} className="text-gray-600" />
                </button>

                {/* Report Header */}
                <div className="border-b border-gray-100 pb-8 mb-8 text-center">
                    <div className="flex justify-center mb-4">
                        <div className="w-16 h-16 bg-blue-600 rounded-2xl flex items-center justify-center shadow-lg shadow-blue-200 text-white">
                            <FileText size={32} />
                        </div>
                    </div>
                    <h1 className="text-3xl font-bold text-gray-900 mb-2">System Analysis Report</h1>
                    <p className="text-gray-500 font-medium">{currentDate}</p>
                    <p className="text-gray-400 text-sm mt-1">Generated by Venue Finder Admin</p>
                </div>

                {/* Key Metrics Grid */}
                <div className="grid grid-cols-2 md:grid-cols-4 gap-6 mb-10">
                    <div className="bg-gray-50 p-6 rounded-2xl border border-gray-100 text-center print:border-gray-200">
                        <p className="text-xs font-bold text-gray-500 uppercase mb-2">Total Venues</p>
                        <p className="text-3xl font-bold text-gray-900">{stats.totalVenues}</p>
                        <p className="text-xs font-bold text-green-600 mt-2 bg-green-50 inline-block px-2 py-1 rounded-lg">+2.5% vs last month</p>
                    </div>
                    <div className="bg-gray-50 p-6 rounded-2xl border border-gray-100 text-center print:border-gray-200">
                        <p className="text-xs font-bold text-gray-500 uppercase mb-2">Total Bookings</p>
                        <p className="text-3xl font-bold text-gray-900">{stats.totalBookings}</p>
                        <p className="text-xs font-bold text-green-600 mt-2 bg-green-50 inline-block px-2 py-1 rounded-lg">+12% vs last month</p>
                    </div>
                    <div className="bg-gray-50 p-6 rounded-2xl border border-gray-100 text-center print:border-gray-200">
                        <p className="text-xs font-bold text-gray-500 uppercase mb-2">Total Revenue</p>
                        <p className="text-3xl font-bold text-blue-600">{stats.totalRevenue}</p>
                        <p className="text-xs font-bold text-green-600 mt-2 bg-green-50 inline-block px-2 py-1 rounded-lg">+8.4% vs last month</p>
                    </div>
                    <div className="bg-gray-50 p-6 rounded-2xl border border-gray-100 text-center print:border-gray-200">
                        <p className="text-xs font-bold text-gray-500 uppercase mb-2">Avg Rating</p>
                        <p className="text-3xl font-bold text-yellow-500">{stats.avgRating}</p>
                        <p className="text-xs font-bold text-gray-400 mt-2 bg-gray-100 inline-block px-2 py-1 rounded-lg">Stable</p>
                    </div>
                </div>

                {/* Top Venues Section */}
                <div className="mb-10 page-break-inside-avoid">
                    <div className="flex items-center gap-3 mb-6">
                        <Activity size={20} className="text-blue-600" />
                        <h2 className="text-xl font-bold text-gray-900">Top Performing Venues</h2>
                    </div>
                    <div className="bg-white border border-gray-200 rounded-xl overflow-hidden">
                        <table className="w-full text-left text-sm">
                            <thead className="bg-gray-50 border-b border-gray-200 text-gray-500 uppercase text-xs font-bold">
                                <tr>
                                    <th className="px-6 py-3">Rank</th>
                                    <th className="px-6 py-3">Venue Name</th>
                                    <th className="px-6 py-3">Location</th>
                                    <th className="px-6 py-3 flex justify-end">Rating</th>
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-gray-100">
                                {topVenues.length > 0 ? (
                                    topVenues.map((venue, index) => (
                                        <tr key={venue.venue_id}>
                                            <td className="px-6 py-4 font-bold text-gray-900">{index + 1}</td>
                                            <td className="px-6 py-4 font-medium">{venue.name}</td>
                                            <td className="px-6 py-4 text-gray-500">{venue.city}</td>
                                            <td className="px-6 py-4 text-right font-bold text-gray-900">{venue.rating} ⭐</td>
                                        </tr>
                                    ))
                                ) : (
                                    <tr><td colSpan="4" className="px-6 py-8 text-center text-gray-400">No data available</td></tr>
                                )}
                            </tbody>
                        </table>
                    </div>
                </div>



                {/* Footer / Report Info */}
                <div className="border-t border-gray-100 pt-8 flex justify-between items-center text-xs text-gray-400">
                    <p>Confidential Report • Internal Use Only</p>
                    <p>Venue Finder Inc.</p>
                </div>

                {/* Action Buttons */}
                <div className="mt-8 flex justify-end gap-3 sticky bottom-0 bg-white/90 backdrop-blur-sm p-4 border-t border-gray-100 -mx-8 -mb-10 rounded-b-3xl">
                    <button
                        onClick={onClose}
                        className="px-6 py-2.5 bg-gray-900 text-white font-medium rounded-xl hover:bg-black transition-colors shadow-lg shadow-gray-200"
                    >
                        Close
                    </button>
                </div>

            </div>
        </div>
    );
};

export default DashboardReportModal;
